# SPDX-FileCopyrightText: 2019-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

layout:
  center:
    lat: 40.075
    lng: 116.24
  zoom: 0
  locationsscale: 1.25
  fademap: false
  showroutes: false
  showpower: false
routeEndPoints:
  -
    start:
      lat: 40.07633
      lng: 116.23637
    end:
      lat: 40.07476
      lng: 116.24432
wayPointRoute: true
directRoute: true
nodes:
  node1:
    gnbid: 20819
    controllers:
    - e2t-1
    servicemodels:
    - kpm2
    cells:
    - 87893173159116801
    status: stopped
  node2:
    gnbid: 20820
    controllers:
    - e2t-1
    servicemodels:
    - kpm2
    cells:
    - 87893173159133185
    status: stopped
cells:
  cell1:
    ncgi: 87893173159116801
    sector:
      center:
        lat: 40.07515
        lng: 116.23983
      azimuth: 0
      arc: 120
      tilt: 1
      height: 43
    color: green
    maxues: 99999
    neighbors:
    - 87893173159133185
    txpowerdb: 11
    measurementparams:
      timetotrigger: 0
      frequencyoffset: 0
      pcellindividualoffset: 0
      ncellindividualoffsets: {}
      hysteresis: 0
      eventa3params:
        a3offset: 0
        reportonleave: false
    pci: 218
    earfcn: 42
    celltype: 2
    rrcidlecount: 0
    rrcconnectedcount: 0
  cell2:
    ncgi: 87893173159133185
    sector:
      center:
        lat: 40.0742
        lng: 116.243
      azimuth: 0
      arc: 120
      tilt: -15
      height: 46
    color: green
    maxues: 99999
    neighbors:
    - 87893173159116801
    txpowerdb: 11
    measurementparams:
      timetotrigger: 0
      frequencyoffset: 0
      pcellindividualoffset: 0
      ncellindividualoffsets: {}
      hysteresis: 0
      eventa3params:
        a3offset: 0
        reportonleave: false
    pci: 115
    earfcn: 45
    celltype: 2
    rrcidlecount: 0
    rrcconnectedcount: 0
controllers:
  e2t-1:
    id: e2t-1
    address: 192.168.127.113
    port: 36401
servicemodels:
  kpm2:
    id: 4
    description: kpm2 service model
    version: 1.0.0
  mho:
    id: 5
    description: mho service model
    version: 1.0.0
  rcpre2:
    id: 3
    description: rcpre2 service model
    version: 1.0.0
rrcStateChangesDisabled: true
initialRrcState: "connected"
ueCount: 1
ueCountPerCell: 15
plmnID: "138426"
plmnNumber: 1279014
apiKey: ""
localConfigs:
  sctpClient:
    sctpClientBind: true
    id: sctp-client-1
    address: 192.168.127.113
#    address: 192.168.126.182